INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (545,1,'Career branch','Astronaut (Space Ranger)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (546,1,'Career branch','Astronaut (Interstellar Smuggler)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (547,1,'Career branch','Athlete (Professional Athlete)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (548,1,'Career branch','Athlete (Bodybuilder)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (549,1,'Career branch','Business (Management)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (550,1,'Career branch','Business (Investor)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (551,1,'Career branch','Criminal (Boss)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (552,1,'Career branch','Criminal (Oracle)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (553,1,'Career branch','Culinary (Chef)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (554,1,'Career branch','Culinary (Mixologist)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (555,1,'Career branch','Entertainer (Musician)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (556,1,'Career branch','Entertainer (Comedian)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (557,1,'Career branch','Freelance Artist');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (558,1,'Career branch','Freelance Programmer');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (559,1,'Career branch','Freelance Writer');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (560,1,'Career branch','Painter (Master of the Real)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (561,1,'Career branch','Painter (Patron of the Arts)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (562,1,'Career branch','Secret Agent (Diamond Agent)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (563,1,'Career branch','Secret Agent (Villain)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (564,1,'Career branch','Style Influencer (Stylist)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (565,1,'Career branch','Style Influencer (Trend Setter)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (566,1,'Career branch','Tech Guru (eSport Gamer)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (567,1,'Career branch','Tech Guru (Start-up Entrepreneur)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (568,1,'Career branch','Writer (Author)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (569,1,'Career branch','Writer (Journalist)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (570,17,'Career branch','Critic (Arts Critic)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (571,17,'Career branch','Critic (Food Critic)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (572,17,'Career branch','Politician (Politician)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (573,17,'Career branch','Politician (Charity Organizer)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (574,17,'Career branch','Social Media (Internet Personality)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (575,17,'Career branch','Social Media (Public Relations)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (576,28,'Career branch','Gardener (Botanist)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (577,28,'Career branch','Gardener (Floral Designer)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (578,30,'Career branch','Military (Covert Operator)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (579,30,'Career branch','Military (Officer)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (580,31,'Career branch','Conservationist (Marine Biologist)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (581,31,'Career branch','Freelance Fashion Photographer');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (582,36,'Career branch','Civil Designer (Civit Planner)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (583,36,'Career branch','Civil Designer (Green Technician)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (584,36,'Career branch','Freelance Crafter');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (585,39,'Career branch','Salaryperson (Expert)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (586,39,'Career branch','Salaryperson (Supervisor)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (587,84,'Career branch','Romance Consultant (Matchmaker)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (588,84,'Career branch','Romance Consultant (Relationship Counselor)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (589,88,'Career branch','Undertaker (Funeral Director)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (590,88,'Career branch','Undertaker (Mortician)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (591,104,'Career branch','Naturopath (Apothecurist)');
INSERT INTO sims4.addon_feature (feature_id,addon_id,feature_type,feature_name) VALUES (592,104,'Career branch','Naturopath (Lifestyle Coaching)');
